### ISSUE TITLE
Button titles are not translated

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio-Web#105]
we currently use title attributes on icon buttons to provide tooltips like so:

<img width="209" alt="image" src="https://user-images.githubusercontent.com/14815080/219107610-1894fd15-c6a7-4449-8e7b-03149db74936.png">

These are only in English though, and the text of them shouldn't be hardcoded, it should return text from our `returnTranslation` method.

**Comment by dhdaines** [comment]
fixed in #118
