### ISSUE TITLE
Add to README.md how to launch studio-web in French locally

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#115]
The best recommendation on how to launch studio-web in French should be documented in the top-level README.md file.

**Comment by dhdaines** [comment]
It's in there, isn't it?

> Ou en français:
> 
>     nx serve studio-web --configuration=development-fr

**Comment by dhdaines** [comment]
(fixed in #111)

**Comment by joanise** [comment]
Doh! I wasn't looking at the latest version, sorry.

**Comment by dhdaines** [comment]
Just in case, I added even more instructions :)
