### ISSUE TITLE
Long delay between steps 1 and 2 on mothertongues in French

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#116]
When I use 
https://readalong-studio.mothertongues.org/fr/
and create a read along, the first time, it can take 5 to 10 seconds with no user feedback.

The ss progress bar is visible for about a second, so alignment is presumably complete, but I guess it has to load the web-component js files or something like that, and in that case there is no user feedback, so it just looks like it's frozen, when in fact I assume it's loading stuff.

It would be nice for the progress bar, or something, to keep moving in one way or another while we're waiting for stuff to load.

**Comment by joanise** [comment]
With cache disabled, it looks like loading all those polyfills links is the biggest chunks:

![image](https://user-images.githubusercontent.com/33264708/219426964-108e2fda-975b-4c7d-a530-51f2ad25a3b8.png)

I know it doesn't look that slow here, but when I first ran it fresh, it felt quite a bit longer.

And now I just reran it with the cache enabled, and this was egregious:

![image](https://user-images.githubusercontent.com/33264708/219427837-86d2bfd4-9251-4a47-a351-0083d787aff8.png)

But third time's the charm, it only took 223ms when I did it a second time with the cache enabled.

So... it's kind of just a first time only problem, but I'd still like some spinner or visible thing while we're loading stuff, so the user knows there's something happening. I've had several situations in the last few days where I thought it was just broken, went away to do something else in another window, and then oops it appeared. We probably can't avoid that, but we should make it so the user knows it's happening.

**Comment by joanise** [comment]
This is funny, though:
![image](https://user-images.githubusercontent.com/33264708/219430330-17a25fb8-0c91-4256-9f7b-420da086e99b.png)
even when things were fast, it's still spending 60ms confirming the cache is still up to date for those two 302's...

**Comment by joanise** [comment]
As for the 39s + 24s 302's above, I wonder if it might have been just after a redeploy on the server side, since we've been actively pushing to `main`.

**Comment by dhdaines** [comment]
> As for the 39s + 24s 302's above, I wonder if it might have been just after a redeploy on the server side, since we've been actively pushing to `main`.

yeah, probably that! sorry!

**Comment by joanise** [comment]
No apologies required, it was good to observe it.

**Comment by dhdaines** [comment]
The polyfills chunks are actually the model files for soundswallower, which are several megabytes in size and can't really be compressed - unfortunately at the moment we can't provide exact progress whlie loading them, but we *can* perhaps change the progress bar to do a wavy thing while we call `decoder.initialize()`.  I had thought it was doing this but apparently not, I can look at it.

**Comment by dhdaines** [comment]
This is probably fixed by #122

**Comment by roedoejet** [comment]
Fixed by https://github.com/ReadAlongs/Web-Component/issues/122 until proven otherwise :)
