### ISSUE TITLE
Fix translations in French

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio-Web#117]
Currently there are some missing translations at https://readalong-studio.mothertongues.org/fr/ on Step 2.

![image](https://user-images.githubusercontent.com/14815080/219468194-7f371c80-2503-4fe7-b795-64f81f6826a9.png)

**Comment by roedoejet** [comment]
The "You can edit the page" in Studio-Web is not translated. In Web-C, the "Upload an image..." is not translated, nor are the titles on buttons.

![image](https://user-images.githubusercontent.com/14815080/219480437-d90cfe3a-67df-4b3d-89a0-2eae125793ae.png)

**Comment by roedoejet** [comment]
Translations for the new steps in the tour also need to be added. See https://github.com/ReadAlongs/Web-Component/pull/119

**Comment by dhdaines** [comment]
Fixed in #118
