### ISSUE TITLE
"contact us" link currently goes nowhere

### ISSUE THREAD

**Issue by dhdaines** [ReadAlongs/Studio-Web#124]
Ideally we should pull it from package.json

**Comment by joanise** [comment]
I'm not sure I want a real e-mail address in here. How about a link to a project page? Which page would be our logical project page? https://readalongs.github.io/ICLDC-Docs/ would be a find choice during ICLDC, I guess.

**Comment by dhdaines** [comment]
Yeah, that makes sense, we can always change it later!

**Comment by joanise** [comment]
We now use `readalong.studio@gmail.com` as the contact us e-mail address.
