### ISSUE TITLE
"Server Error" flashes on screen when loading Studio Web

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio-Web#128]
Hard to get a screenshot because it happens momentarily, but the "Server Error" div shows up briefly. This should only load if there is actually a server error, not before the server has loaded.

**Comment by dhdaines** [comment]
Hi, yeah, this *should* be fixed in #125 - the upload component is conditionalized on `langs` being loaded, and the server error is too.

**Comment by dhdaines** [comment]
Interesting to know that it happened already before I moved the `/langs` loading into `ngOnInit` though!
