### ISSUE TITLE
Slow initial alignment due to loading model files

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio-Web#130]
currently we load the model assets (`/model/en-us/*`) only when we actually run the aligner, and since these files are over 6MB this can take quite a while depending on the connection. We should consider how to non-lazily load at least the four biggest files (mdef, means, variances, sendump) on application load or something.

**Comment by dhdaines** [comment]
Ah, good idea... we can do this by creating a `Decoder` on application load and simply throwing it away, as the files will then be cached afterwards.

**Comment by dhdaines** [comment]
If we also do this in `ngOnInit` of the upload component (or the SoundSwallower service?) we can show a message or spinner of some sort...
