### ISSUE TITLE
Recording fails silently

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio-Web#136]
Sometimes recordings look like they've happened, but there's only silence and there is no warning given to the user. This seems to happen on my laptop when my headphones aren't plugged in - I suspect this has something to do with the browser choosing the wrong input or something, but I think we should at least have a warning if we don't record any input.

**Comment by dhdaines** [comment]
Yup, this is exactly the problem I was having on the iMacs at school.  We need to check for a zero-length input somehow, I think we can just check `blob.size === 0` on what the microphone component returns?

**Comment by roedoejet** [comment]
hm, no , looks like there is still a size for me.

**Comment by roedoejet** [comment]
This is what I get when I record the word "test" with my headphones unattached vs attached
```
Blob {size: 609, type: 'audio/webm'}
Blob {size: 6737, type: 'audio/webm'}
```

**Comment by roedoejet** [comment]
maybe `blob.size < 1000` ? or even a bit higher?

**Comment by dhdaines** [comment]
Hmm - you do get a "decoding error" later on when you try to align, right?

**Comment by roedoejet** [comment]
yep, I get the "Error: No alignments were found." error

**Comment by dhdaines** [comment]
Ah, that's a different error than the one I was thinking of.  So it is a valid WebM audio file, just a silent one (the file is small because silence compressed down to almost nothing)

**Comment by dhdaines** [comment]
This is harder to deal with, but we should try, since it will be a common failure mode.  I will think a bit about it - we would maybe want to lump it in with other alignment failures, and suggest in a troubleshooting guide (or even the error message) that the first thing should be to check that there's actually something audible in the recording.

**Comment by roedoejet** [comment]
yea, I am struggling to get the size less than 3000 if my microphone is actually working.

**Comment by roedoejet** [comment]
I think it might be safe to add a "Sorry, we couldn't hear anything" type error toast if the size is less than 2000

**Comment by dhdaines** [comment]
That does seem like a reasonable heuristic :)

**Comment by roedoejet** [comment]
ok I added a PR with this (that needs french). Do you agree with where I put this? Given that we're starting to develop different errors for the microphone, maybe we should have a different err coding system than just the strings?

**Comment by joanise** [comment]
I've noticed problems with recording many times, I'll test your PR to see if it's better. I find often when I first start using my mike, it's like I have to rev it: the first few times, it can be quite slow to start recording, so I might be speaking but it's not recording yet, and eventually it get better.

**Comment by joanise** [comment]
Translating your message.
