### ISSUE TITLE
Unable to record from my android phone

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#143]
I tried to show off the app to a friend this week-end, and I did not succeed in activating the recording function on my Android phone. I had to do the tour and use Aidan's canned data instead.

**Comment by dhdaines** [comment]
Hmm.  Recording works fine on my phone (Android 12, LG Velvet).

What version of Android, browser, phone is yours?

**Comment by joanise** [comment]
The phone is a Galaxy S20 FE
Android 13
Browser: Chrome 110.0.5481.65

Doh! I think I just figured out the problem. I should have read the error message: "NotAllowedError: Permission denied"...

**Comment by joanise** [comment]
It took me a while to figure out how to give Chrome microphone permissions, but once I did so, I was able to record and align. The RA worked fine. I only recorded "This is a test." but alignment is perfect. :)

**Comment by dhdaines** [comment]
Closing it then! it works on my phone
