### ISSUE TITLE
Demo-component can get two scroll bars instead of just one

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#168]
With #166, 
the bug reported in #153 is much improved, but now there are potentially two scroll bars when the vertical height of the screen is small:
![image](https://user-images.githubusercontent.com/33264708/221198878-9b5c8a63-d705-40f1-8ebd-7d5411f92043.png)

While it's possible to see everything, it's very confusing the figure out where you have to scroll to get the right behaviour. Better would be to force the demo.component to always occupy all the space it needs in its parent component, and have only the parent component have a scroll bar.

On a computer, you see the two scroll bars like in my screen shot, but on a cell phone you have to guess where you're supposed to drag to get scrolling where you want it to go.

The same thing happens with the downloaded single-file HTML. Making my viewport even smaller, I was able to have three competing scroll bars
![image](https://user-images.githubusercontent.com/33264708/221199578-87152ba4-ab0b-48c2-ab19-3b5c0bb38560.png)

**Comment by dhdaines** [comment]
Oof, yeah, multiple scroll bars like that are the bane of my existence, lots of software seems to assume everybody has 3560x1920 screens these days

**Comment by joanise** [comment]
Yeah, I agreed, I find them really annoying. Even more annoying to me is that frameworks gleefully create them even though we didn't ask for it, and you have to work hard at avoiding them!
