### ISSUE TITLE
Add readme to publish with ngx-web-component and web-component

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio-Web#175]
Currently the pages are empty https://www.npmjs.com/package/@readalongs/web-component https://www.npmjs.com/package/@readalongs/ngx-web-component

**Comment by deltork** [comment]
I think Eric has fixed this now

**Comment by joanise** [comment]
Yes, this is fixed, although it won't be effective until the next patch release. Should we publish a patch now @deltork ?
