### ISSUE TITLE
Studio-Web: let the user see g2p errors and warnings

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#178]
Right now, a catastrophic g2p error gives the user a 422. The g2p errors can be found in the `"log"` field in the response, but no one but developers will be able to access them.

It would be nice to devise a means to let the user see the g2p problems in a friendlier way, both in case of g2p warnings (which were handled via und) and fatal g2p errors even und could not handle (although those should not happen anymore since we've put in the fix to handle Arabic presentation forms).

**Comment by dhdaines** [comment]
Working on this in #181

**Comment by joanise** [comment]
Done
