### ISSUE TITLE
release ci fails to push changes back

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio-Web#188]
The `release` workflow failed so we had to bump versions back manually (https://github.com/ReadAlongs/Web-Component/commit/ca1ad51b7be7e73b7321865681bc890fb1621a89). It seems this is because CI doesn't have permission to publish to `release`. Also `:set-output name=TAG_VERSION::$(npm view @readalongs/web-component version)` got set incorrectly so the tag was for the version below. I had to update that manually as well.

**Comment by joanise** [comment]
Will fix this soon, via a test repo.

**Comment by joanise** [comment]
Fixed by #195
