### ISSUE TITLE
If the image is too "tall" we can't see the whole thing

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#190]
Reported by a participant at CWILTS seminar

Reproduced slightly differently by Eric.

I created a file .png with 850 pixels wide, 1100 pixels high, and added it to a read-along created using Studio-Web using my ej-fra.txt and ej-fra.m4a in Studio/test/data, and we cannot see the whole image.
![image](https://user-images.githubusercontent.com/33264708/222251621-e0be9c4c-6ea9-4583-be12-c8c229922f87.png)
![image](https://user-images.githubusercontent.com/33264708/222251667-2772eefb-cdaa-432d-a43b-140018a982f6.png)
(The real image is quite a bit taller, the bottom cannot be seen or scrolled to.

**Comment by joanise** [comment]
I don't see how to attach a file to an issue, I'll share it in Slack.

**Comment by joanise** [comment]
The CWILTS participant had a behaviour that was a bit worse, the image was shifted halfway down the page and at least half hidden, but I cannot reproduce that yet.

**Comment by deltork** [comment]
We need to add` max-height:$page-size; `after line https://github.com/ReadAlongs/Web-Component/blob/main/packages/web-component/src/scss/modules/_pages.scss#L59
to fix that

**Comment by joanise** [comment]
Well, darn. That makes sense, but I tried to do it, and it doesn't work for me. I can't get the max-height to have any impact on the image, even when I give it ridiculously small values.

**Comment by deltork** [comment]
Can you test the file with branch issue-190 https://github.com/ReadAlongs/Web-Component/tree/issue-190

**Comment by joanise** [comment]
@deltork Tested, the problem is still the same, sorry. I shared the test image with you in Slack, did you find it?

**Comment by joanise** [comment]
Just added `850x1100.png` into `packages/web-component/test-data/` on the `issue-190` branch so the test file is attached to the problem. Maybe we could use it in some unit testing, actually?

**Comment by joanise** [comment]
Fixed by #217
