### ISSUE TITLE
Studio-Web does not stop using the microphone when it stops recording

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#213]
Testing on an iPad, my kid noticed the app is still recording when you stop recording. More precisely, the app is still using the microphone, even though we're not recording anymore. On Chrome, you see the same thing:
![image](https://github.com/ReadAlongs/Web-Component/assets/33264708/d2de5f92-e78b-4255-ad1b-3a95821f98c7)

and that can be taken as suspicious activity. We should figure out how to stop the microphone once the user clicks on stop recording.

Before you start recording, it shows this:
![image](https://github.com/ReadAlongs/Web-Component/assets/33264708/c773cac3-257f-4c6e-88af-7edda1f3b69c)
and that's what it should go back to once we click stop.

**Comment by dhdaines** [comment]
Hmm - I seem to remember that it used to release the microphone after recording, not sure if it changed recently.  I'll look into it quickly in a second.

**Comment by dhdaines** [comment]
Ah, like most things Web Audio, the big brains at Apple and Google voted in favour of needless complexity in all things.  Basically you have to keep a reference to the `MediaStream` that you originally got from the browser and then iterate over its "tracks" (of which there is only one) and close them.  I'll make a PR in a second.

**Comment by dhdaines** [comment]
(see https://stackoverflow.com/questions/11642926/stop-close-webcam-stream-which-is-opened-by-navigator-mediadevices-getusermedia)

**Comment by joanise** [comment]
Ah, thanks for doing the research. At least it appears easy to fix.

**Comment by joanise** [comment]
Fixed by #214
