### ISSUE TITLE
Viewing a single-file HTML does not work on iPad [edited, was: Downloading the Offline HTML on an iPad produces something useless]

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#216]
Steps to reproduce:
iPadOS 16.5.1, Safari
create a readalong
Click the download arrow. with Offline HTML selected

Result: a file is downloaded, but when you try to open it on the iPad you can see the title and subtitle, and nothing else.

Note: the other formats all download just fine, it's just the .html file that's broken.

**Comment by joanise** [comment]
All these iPad problems make me think we should say iPads are not supported for creating contents...

**Comment by joanise** [comment]
Tested the same on my Android phone, and it works fine. It is indeed an iPad problem.

**Comment by roedoejet** [comment]
can you send that html file? have you tried running another html file generated elsewhere on iPad?

**Comment by joanise** [comment]
I'm not sure how to make that happen at the moment, since I don't have e-mail configured on that device, or any other exchange mechanism. But yes, this is the right thing to do, I'll try to figure out a way.

**Comment by joanise** [comment]
OK, I got the RA produced on the iPad on my computer and it was fine. But I made an RA on my computer and tried to open the downloaded single-file .html file and that gives me the same problem: I can only see the title and subtitle and a blank page underneath it. So the WebComponent is not being launched correctly on this device.

**Comment by roedoejet** [comment]
is this on safari or chrome? or both?

**Comment by roedoejet** [comment]
> OK, I got the RA produced on the iPad on my computer and it was fine. But I made an RA on my computer and tried to open the downloaded single-file .html file and that gives me the same problem: I can only see the title and subtitle and a blank page underneath it. So the WebComponent is not being launched correctly on this device.

is this on safari or chrome? or both?

**Comment by joanise** [comment]
All Safari.

My kid has helped me troubleshoot this. The problem happens on his iPhone too, when you try to open the file, it does not actually launch the browser at all, it's launching some kind of preview instead. We have not found a way on either his phone or the tablet to force actually opening the file in Safari proper.

**Comment by joanise** [comment]
Just tested in Chrome too: same results, the .html file you download can't be opened in Chrome (at least not in any obvious way).

**Comment by joanise** [comment]
Tested in Firefox, the results are wrong in a different way: I still can't open a downloaded file, but the download button, instead of actually downloading, displays the blob (yes, the URL bar actually says `blob:`). Here the RA is correct, but I don't see how to actually download it. And having installed Firefox, the downloaded HTML files still can't be opened in Firefox, only in the broken preview.

**Comment by roedoejet** [comment]
Well this is what we get for not forking over the cash to browserstack I guess 🫢😅

Apparently Microsoft edge might work on iPad and iOS for local html files. We should talk about all this at the next RAS meeting but yes, suffice to say, maybe just stick with the laptop for now

**Comment by dhdaines** [comment]
Yes, this is a consequence of Apple's slightly paranoid security model which tries to prevent iPhones and iPads from behaving in any way remotely resembling an actual computer. See: https://apple.stackexchange.com/questions/38944/can-i-save-an-html-file-to-my-iphone-and-open-in-safari

**Comment by joanise** [comment]
Or install Edge: this gives you an open in Edge option for local files.
https://stackoverflow.com/questions/67581426/how-to-open-a-local-html-file-in-safari-on-an-ipad

**Comment by joanise** [comment]
I tested, and yes, I can open the downloaded file in Edge. It's many clicks, but it's doable.

**Comment by joanise** [comment]
Closing this. We now have to remember that the work-around is as ugly as installing MS Edge on an iPad...
