### ISSUE TITLE
Angular 15 is EOL in May 2024, so bump to Angular 17.

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#239]
I did a first attempt just using the automatic tool to do 15->16, and it was not straightforward, there are interactions with other dependencies. So this will not be an easy task, but we need to tackle it at some point because we'll be stuck unable to handle CVEs soon enough if we don't.

**Comment by dhdaines** [comment]
Deleting package-lock.json often helps with dependency hell... Since I'm back in Angular land lately I can take a look at this shortly

**Comment by joanise** [comment]
Darn, this is now preventing us from fixing this high-severity CVE:
https://github.com/ReadAlongs/Web-Component/security/dependabot/79

**Comment by dhdaines** [comment]
Well, it's again a CVE that only affects the development environment, but I will get on the 15-17 update ASAP, probably this evening!

**Comment by dhdaines** [comment]
fixed in #247
