### ISSUE TITLE
CI randomly fails in basic.cy.js, apparently related to scrolling

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#275]
Intermittent CI workflow failure, so this is hard to reproduce. But see
https://github.com/ReadAlongs/Studio-Web/actions/runs/8903159213/job/24450409271
https://github.com/ReadAlongs/Studio-Web/actions/runs/8900297255/job/24441553848
https://github.com/ReadAlongs/Studio-Web/actions/runs/8885442422/job/24396804150

Now, the patch 
```
-    } else {
+    } else if (play_id) {
```
to `read-along.tsx` modified the error message but unfortunately did not actually make the problem go away.

**Comment by joanise** [comment]
Oh, @roedoejet has done work on the web-component in #267. Aidan, any chance you fixed this bug here already?

**Comment by roedoejet** [comment]
No, I can't reproduce it locally

**Comment by joanise** [comment]
I've only ever seen it in CI, so I'm not surprised...

**Comment by deltork** [comment]
How do we test this? Run the CI test 3? or 4? times?

**Comment by joanise** [comment]
Frankly I don't know. I can't reliably make it fail, so I don't know how to test that it's been fixed! The worst kind of bug...

**Comment by dhdaines** [comment]
Looks to me like some code has called an `async` function without `await` and thus it is running at some future unpredictable time?
