### ISSUE TITLE
Add an option to trigger or disable auto scrolling between pages

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#30]
Sometimes, it's best to have a RA go from page to page automatically, sometimes it's best to make the user click on "next page".

Add an option to control this behaviour 
 - as an attribute to the web component, and/or
 - in a gear menu the user can control or both

The UI will need a previous page and a next page button.

**Comment by deltork** [comment]
[DONE] see branch   #patch.page_transition.
Opted for both user and content creator control of this feature.
When  this mode is activated in the WC,  it will pause at the end of the page and only resumes when the user clicks the play button.
(see test-data/index-pause-at-end-of-page.html)

**Comment by joanise** [comment]
+1 from the W̱SÁNEĆ school board.
