### ISSUE TITLE
Fix page transitions on slower computers

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#32]
On slower computers, sometimes the second word on the next page is already playing when the transition to the next page has completed.

We've brain-stormed all sorts of ideas to fix this:
 - have the Web-C pause the audio while waiting for the page transition
 - switch the page transition mode from "smooth" to "auto" so that it's instant of slower computers
 - auto pause between pages, making the user request moving to and starting the next page

Bigger ideas:
 - augment the XML to declare the time range of pages to flip pages on that instead of on the word, (BREAKING change)
 - use the `bare` mode in Studio and have the Web-C insert a pause only as long as needed before starting to play the first word on the next page (to a minimum hard-coded delay per transition, or waiting for the event that says the transition is complete)

**Comment by joanise** [comment]
Related: #30 #34 #35

**Comment by deltork** [comment]
I think this issue has been resolved
