### ISSUE TITLE
The download format option disappears on tablet-size screens and smaller

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#333]
When the viewport width is <=992, the Output Format selector next to the download button, in both the Editor and the Studio, disappears and the user can only download single-file HTML.

**Comment by deltork** [comment]
see PR #334 
![image](https://github.com/user-attachments/assets/f34e50b9-cf89-42d7-a07e-7e656737c78d)
![image](https://github.com/user-attachments/assets/ef9aad82-14a0-4fe4-a525-db4c53068a2f)
