### ISSUE TITLE
Studio-Web: click "Go to next step" when the web_api is not running just hangs

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#80]
I had Studio-Web served, but web_api forgotten, when I click on "Go to the next step!", the app just hangs, no progress bar, not errors, just that button goes gray.

Desired behaviour: there should be an error message. It could say "ReadAlong-Studio server error, please contact the administrators of this site to make sure the web API is running"?

I don't much like my draft message, but I would like the message to convey:
 - you, the user, did nothing wrong ― it's us, not you
 - enough information that the admin (or the developer) will immediately know what it means.

Idea: when `/langs` fails, we could already emit such a message: while not having the list of languages is not fatal, it's a symptom indicating `/assemble` will almost certainly fail too, and we should warn the user about that early so they don't waste their time with a broken deployment.

**Comment by dhdaines** [comment]
fixed in #120
