### ISSUE TITLE
Incompatible with Safari

### ISSUE THREAD

**Issue by dhdaines** [ReadAlongs/Studio-Web#97]
Results vary depending on the version/platform.  On iOS 12 it simply refuses to load.  Results may vary on Mac OS.

**Comment by joanise** [comment]
@littell also has a test iPad he can do some testing with, but just as validation, not as dev.

**Comment by dhdaines** [comment]
I made sure to get a Mac powerful enough to run iOS dev tools, at least, I hope so (is 16GB of RAM and a 2.9GHz Core i7 enough?) so we'll see...

**Comment by dhdaines** [comment]
Tested on Safari 15.6.1, it does actually seem to mostly work.  The only issues I found are:

- .mp3 input is *not* supported (but .m4a is)  - we get a "decoding failed" error
- playing back the recorded audio (in webm format) doesn't work (surprisingly, since the browser recorded it!)

**Comment by dhdaines** [comment]
The failure I had before was that the microphone (which was actually an external USB DAC, I am in a media lab) did not work and gave a zero-length output file.  This also gives a "decoding failed" error, which we don't see - it just refuses to go to the second page.  I will see what the best way to catch this is (which might just be checking for a zero-length recording)

**Comment by dhdaines** [comment]
if we don't want to add a package for mp3 decoding, we can always make it so that we support mp3 except on safari where we support m4a...

**Comment by dhdaines** [comment]
We now report the error properly with #120

**Comment by dhdaines** [comment]
The loading problem is due to previous versions of Safari not fully supporting WebAssembly, and most likely due to lack of support for streaming compilation.  It is possible to test for this at runtime with https://github.com/GoogleChromeLabs/wasm-feature-detect - but at a minimum I will just produce a version of SoundSwallower that avoids this and other recent WASM features which we could use by default, as it isn't big enough that we should really need those features...

**Comment by dhdaines** [comment]
Closing this as Safari 14 and over are supported, and Angular won't let us support anything earlier.
